package catalog

import (
	"os"
	"reflect"
	"strings"
	"testing"

	"go.yaml.in/yaml/v3"
)

func TestCatalogV02FrozenCompatibility(t *testing.T) {
	if err := Validate(); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile("testdata/classification-v0.2.yaml")
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	for _, want := range []string{
		"Never regenerate this file",
		"64 filenames, 40 directories, 32 suffixes, 120 extensions",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("frozen fixture missing %q", want)
		}
	}
	var document classificationFixtureDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	if document.CatalogVersion != 1 || len(document.Cases) != FrozenV02EntryCount {
		t.Fatalf("frozen v0.2 fixture = version %d, cases %d", document.CatalogVersion, len(document.Cases))
	}
	counts := map[MatchSource]int{}
	for _, fixture := range document.Cases {
		got := Classify(fixture.Name, fixture.RelativePath, fixture.Type)
		want := Classification{Kind: fixture.Kind, Roles: fixture.Roles, Source: fixture.Source, MatcherKey: fixture.MatcherKey}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s: got %#v, want %#v", fixture.ID, got, want)
		}
		counts[fixture.Source]++
	}
	wantCounts := map[MatchSource]int{
		SourceFilename:  FrozenV02FilenameEntryCount,
		SourceDirectory: FrozenV02DirectoryEntryCount,
		SourceSuffix:    FrozenV02SuffixEntryCount,
		SourceExtension: FrozenV02ExtensionEntryCount,
	}
	if !reflect.DeepEqual(counts, wantCounts) {
		t.Fatalf("frozen v0.2 groups = %#v, want %#v", counts, wantCounts)
	}
}

func TestFrozenV02FixtureIsNeverAutoGenerated(t *testing.T) {
	writer, err := os.ReadFile("catalog_contract_test.go")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(writer), "classification-v0.2.yaml") {
		t.Fatal("v1 fixture writer must not reference testdata/classification-v0.2.yaml")
	}
	if !strings.Contains(string(writer), "testdata/classification-v1.yaml") {
		t.Fatal("v1 fixture writer must target testdata/classification-v1.yaml")
	}
}
